### ISSUE TITLE
Conan 1 is legacy and on a deprecation path. Please upgrade to Conan 2.

### ISSUE THREAD

**Issue by paddyroddy** [astro-informatics/s2let#55]
Error when attempting to install `pys2let`

```sh
Conan version 1.65.0

-- Conan executing: /Users/paddy/Library/Caches/uv/builds-v0/.tmpqQioyY/bin/conan install /Users/paddy/Library/Caches/uv/sdists-v4/pypi/pys2let/2.2.6/V40OwwhgXzDqxUrh4Xi5c/pys2let-2.2.6.tar.gz/conanfile.txt --remote conancenter --generator cmake_find_package --generator cmake_paths --build missing --settings build_type=Release --settings compiler=apple-clang --settings compiler.version=16.0

-- Configuring incomplete, errors occurred!
--- stderr:
WARN: **************************************************
WARN: *** Conan 1 is legacy and on a deprecation path **
WARN: *********** Please upgrade to Conan 2 ************
WARN: **************************************************
ERROR: Invalid setting '16.0' is not a valid 'settings.compiler.version' value.
Possible values are ['5.0', '5.1', '6.0', '6.1', '7.0', '7.3', '8.0', '8.1', '9.0', '9.1', '10.0', '11.0', '12.0', '13', '13.0', '13.1', '14', '14.0', '15', '15.0']
Read "http://docs.conan.io/en/latest/faq/troubleshooting.html#error-invalid-setting"
CMake Error at _skbuild/macosx-15.0-arm64-3.12/cmake-build/conan.cmake:631 (message):
  Conan install failed='1'
Call Stack (most recent call first):
  cmake/conan_dependencies.cmake:14 (conan_cmake_install)
  CMakeLists.txt:24 (include)


Traceback (most recent call last):
  File "/Users/paddy/Library/Caches/uv/builds-v0/.tmpqQioyY/lib/python3.12/site-packages/skbuild/setuptools_wrap.py", line 660, in setup
    env = cmkr.configure(
          ^^^^^^^^^^^^^^^
  File "/Users/paddy/Library/Caches/uv/builds-v0/.tmpqQioyY/lib/python3.12/site-packages/skbuild/cmaker.py", line 354, in configure
    raise SKBuildError(msg)
```

**Comment by jasonmcewen** [comment]
Seem like this issue has been resolved?  See here: https://github.com/astro-informatics/ssht/pull/71#issuecomment-2397834018

**Comment by paddyroddy** [comment]
No, it's still not working

<details><summary>Logs</summary>
~ via 🐍 v3.13.1 (paddy)
󰂃 9% ❯ cd /tmp; \rm -rf .venv; uv venv; source .venv/bin/activate
direnv: unloading
Using CPython 3.12.7
Creating virtual environment at: .venv
Activate with: source .venv/bin/activate

/tmp via 🐍 v3.12.7 (tmp)
󰂃 9% ❯ uv pip install pys2let
Resolved 2 packages in 4ms
  × Failed to build `pys2let==2.2.6`
  ├─▶ The build backend returned an error
  ╰─▶ Call to `setuptools.build_meta:__legacy__.build_wheel` failed (exit status: 1)

      [stdout]


      --------------------------------------------------------------------------------
      -- Trying 'Ninja' generator
      --------------------------------
      ---------------------------
      ----------------------
      -----------------
      ------------
      -------
      --
      Not searching for unused variables given on the command line.
      -- The C compiler identification is AppleClang 16.0.0.16000026
      -- Detecting C compiler ABI info
      -- Detecting C compiler ABI info - done
      -- Check for working C compiler: /Library/Developer/CommandLineTools/usr/bin/cc - skipped
      -- Detecting C compile features
      -- Detecting C compile features - done
      -- Configuring done (4.7s)
      -- Generating done (0.0s)
      -- Build files have been written to: /Users/paddy/Library/Caches/uv/sdists-v6/pypi/pys2let/2.2.6/SNYIrkROeoiFCI7qqJM4z/src/_cmake_test_compile/build
      --
      -------
      ------------
      -----------------
      ----------------------
      ---------------------------
      --------------------------------
      -- Trying 'Ninja' generator - success
      --------------------------------------------------------------------------------

      Configuring Project
        Working directory:
          /Users/paddy/Library/Caches/uv/sdists-v6/pypi/pys2let/2.2.6/SNYIrkROeoiFCI7qqJM4z/src/_skbuild/macosx-15.0-arm64-3.12/cmake-build
        Command:
          /Users/paddy/Library/Caches/uv/builds-v0/.tmpIzdyeT/lib/python3.12/site-packages/cmake/data/bin/cmake
      /Users/paddy/Library/Caches/uv/sdists-v6/pypi/pys2let/2.2.6/SNYIrkROeoiFCI7qqJM4z/src -G Ninja -DCMAKE_MAKE_PROGRAM:FILEPATH=/Users/paddy/Library/Caches/uv/builds-v0/.tmpIzdyeT/bin/ninja
      --no-warn-unused-cli -DCMAKE_INSTALL_PREFIX:PATH=/Users/paddy/Library/Caches/uv/sdists-v6/pypi/pys2let/2.2.6/SNYIrkROeoiFCI7qqJM4z/src/_skbuild/macosx-15.0-arm64-3.12/cmake-install
      -DPYTHON_VERSION_STRING:STRING=3.12.7 -DSKBUILD:INTERNAL=TRUE -DCMAKE_MODULE_PATH:PATH=/Users/paddy/Library/Caches/uv/builds-v0/.tmpIzdyeT/lib/python3.12/site-packages/skbuild/resources/cmake
      -DPYTHON_EXECUTABLE:PATH=/Users/paddy/Library/Caches/uv/builds-v0/.tmpIzdyeT/bin/python
      -DPYTHON_INCLUDE_DIR:PATH=/Users/paddy/.local/share/uv/python/cpython-3.12.7-macos-aarch64-none/include/python3.12
      -DPython_EXECUTABLE:PATH=/Users/paddy/Library/Caches/uv/builds-v0/.tmpIzdyeT/bin/python -DPython_ROOT_DIR:PATH=/Users/paddy/Library/Caches/uv/builds-v0/.tmpIzdyeT
      -DPython_FIND_REGISTRY:STRING=NEVER -DPython_INCLUDE_DIR:PATH=/Users/paddy/.local/share/uv/python/cpython-3.12.7-macos-aarch64-none/include/python3.12
      -DPython_NumPy_INCLUDE_DIRS:PATH=/Users/paddy/Library/Caches/uv/builds-v0/.tmpIzdyeT/lib/python3.12/site-packages/numpy/_core/include
      -DPython3_EXECUTABLE:PATH=/Users/paddy/Library/Caches/uv/builds-v0/.tmpIzdyeT/bin/python -DPython3_ROOT_DIR:PATH=/Users/paddy/Library/Caches/uv/builds-v0/.tmpIzdyeT
      -DPython3_FIND_REGISTRY:STRING=NEVER -DPython3_INCLUDE_DIR:PATH=/Users/paddy/.local/share/uv/python/cpython-3.12.7-macos-aarch64-none/include/python3.12
      -DPython3_NumPy_INCLUDE_DIRS:PATH=/Users/paddy/Library/Caches/uv/builds-v0/.tmpIzdyeT/lib/python3.12/site-packages/numpy/_core/include
      -DCMAKE_MAKE_PROGRAM:FILEPATH=/Users/paddy/Library/Caches/uv/builds-v0/.tmpIzdyeT/bin/ninja -DBUILD_TESTING:BOOL=OFF -Dconan_deps:BOOL=ON -Dcfitsio:BOOL=ON
      -DCMAKE_POSITION_INDEPENDENT_CODE=ON -DCMAKE_OSX_DEPLOYMENT_TARGET:STRING=15.0 -DCMAKE_OSX_ARCHITECTURES:STRING=arm64 -DCMAKE_BUILD_TYPE:STRING=Release

      Not searching for unused variables given on the command line.
      -- Conan: checking conan executable
      -- Conan: Found program /Users/paddy/Library/Caches/uv/builds-v0/.tmpJqYR4G/bin/conan
      -- Configuring incomplete, errors occurred!

      [stderr]
      CMake Deprecation Warning at CMakeLists.txt:1 (cmake_minimum_required):
        Compatibility with CMake < 3.10 will be removed from a future version of
        CMake.

        Update the VERSION argument <min> value.  Or, use the <min>...<max> syntax
        to tell CMake that the project requires at least <min> but has been updated
        to work with policies introduced by <max> or earlier.


      CMake Error at _skbuild/macosx-15.0-arm64-3.12/cmake-build/conan.cmake:806 (message):
        Conan --version failed='no such file or directory'
      Call Stack (most recent call first):
        _skbuild/macosx-15.0-arm64-3.12/cmake-build/conan.cmake:531 (conan_check)
        cmake/conan_dependencies.cmake:14 (conan_cmake_install)
        CMakeLists.txt:24 (include)


      Traceback (most recent call last):
        File "/Users/paddy/Library/Caches/uv/builds-v0/.tmpIzdyeT/lib/python3.12/site-packages/skbuild/setuptools_wrap.py", line 660, in setup
          env = cmkr.configure(
                ^^^^^^^^^^^^^^^
        File "/Users/paddy/Library/Caches/uv/builds-v0/.tmpIzdyeT/lib/python3.12/site-packages/skbuild/cmaker.py", line 354, in configure
          raise SKBuildError(msg)

      An error occurred while configuring with CMake.
        Command:
          /Users/paddy/Library/Caches/uv/builds-v0/.tmpIzdyeT/lib/python3.12/site-packages/cmake/data/bin/cmake
      /Users/paddy/Library/Caches/uv/sdists-v6/pypi/pys2let/2.2.6/SNYIrkROeoiFCI7qqJM4z/src -G Ninja -DCMAKE_MAKE_PROGRAM:FILEPATH=/Users/paddy/Library/Caches/uv/builds-v0/.tmpIzdyeT/bin/ninja
      --no-warn-unused-cli -DCMAKE_INSTALL_PREFIX:PATH=/Users/paddy/Library/Caches/uv/sdists-v6/pypi/pys2let/2.2.6/SNYIrkROeoiFCI7qqJM4z/src/_skbuild/macosx-15.0-arm64-3.12/cmake-install
      -DPYTHON_VERSION_STRING:STRING=3.12.7 -DSKBUILD:INTERNAL=TRUE -DCMAKE_MODULE_PATH:PATH=/Users/paddy/Library/Caches/uv/builds-v0/.tmpIzdyeT/lib/python3.12/site-packages/skbuild/resources/cmake
      -DPYTHON_EXECUTABLE:PATH=/Users/paddy/Library/Caches/uv/builds-v0/.tmpIzdyeT/bin/python
      -DPYTHON_INCLUDE_DIR:PATH=/Users/paddy/.local/share/uv/python/cpython-3.12.7-macos-aarch64-none/include/python3.12
      -DPython_EXECUTABLE:PATH=/Users/paddy/Library/Caches/uv/builds-v0/.tmpIzdyeT/bin/python -DPython_ROOT_DIR:PATH=/Users/paddy/Library/Caches/uv/builds-v0/.tmpIzdyeT
      -DPython_FIND_REGISTRY:STRING=NEVER -DPython_INCLUDE_DIR:PATH=/Users/paddy/.local/share/uv/python/cpython-3.12.7-macos-aarch64-none/include/python3.12
      -DPython_NumPy_INCLUDE_DIRS:PATH=/Users/paddy/Library/Caches/uv/builds-v0/.tmpIzdyeT/lib/python3.12/site-packages/numpy/_core/include
      -DPython3_EXECUTABLE:PATH=/Users/paddy/Library/Caches/uv/builds-v0/.tmpIzdyeT/bin/python -DPython3_ROOT_DIR:PATH=/Users/paddy/Library/Caches/uv/builds-v0/.tmpIzdyeT
      -DPython3_FIND_REGISTRY:STRING=NEVER -DPython3_INCLUDE_DIR:PATH=/Users/paddy/.local/share/uv/python/cpython-3.12.7-macos-aarch64-none/include/python3.12
      -DPython3_NumPy_INCLUDE_DIRS:PATH=/Users/paddy/Library/Caches/uv/builds-v0/.tmpIzdyeT/lib/python3.12/site-packages/numpy/_core/include
      -DCMAKE_MAKE_PROGRAM:FILEPATH=/Users/paddy/Library/Caches/uv/builds-v0/.tmpIzdyeT/bin/ninja -DBUILD_TESTING:BOOL=OFF -Dconan_deps:BOOL=ON -Dcfitsio:BOOL=ON
      -DCMAKE_POSITION_INDEPENDENT_CODE=ON -DCMAKE_OSX_DEPLOYMENT_TARGET:STRING=15.0 -DCMAKE_OSX_ARCHITECTURES:STRING=arm64 -DCMAKE_BUILD_TYPE:STRING=Release
        Source directory:
          /Users/paddy/Library/Caches/uv/sdists-v6/pypi/pys2let/2.2.6/SNYIrkROeoiFCI7qqJM4z/src
        Working directory:
          /Users/paddy/Library/Caches/uv/sdists-v6/pypi/pys2let/2.2.6/SNYIrkROeoiFCI7qqJM4z/src/_skbuild/macosx-15.0-arm64-3.12/cmake-build
      Please see CMake's output for more information.


      hint: This usually indicates a problem with the package or the build environment.
</details>

**Comment by jasonmcewen** [comment]
Oh no!  Any idea @mdavezac ?

**Comment by mdavezac** [comment]
The recipes are definitely on conan 2: https://conan.io/center/recipes/s2let?version=2.2.6 
But it looks like they were automatically translated by bots from 1 to 2.
So pip was never updated. I don't remember too well how pip builds and publishes things here, but it's likely that the conan recipes downloading ssht are outdated. They should instead refer to the newer ones in conan center.

**Comment by jasonmcewen** [comment]
Hey @mdavezac , can you advise on exactly how we can update things?  

We can do this but are not sure how to proceed.  I don't think anyone on our side is familiar with Conan.

This is becoming a blocker for adding numpy>=2 support for our new s2fft code (which is seeing some interest!) as discussed in [this issue](https://github.com/astro-informatics/s2fft/issues/266).  

If you're interested, we could also add you as a contributor to s2fft for infrastructure work?
